
FROM debian:latest

RUN apt-get update && \
    apt-get install -y netcat-openbsd fortune-mod cowsay
COPY wisecow-app/wisecow.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/wisecow.sh

EXPOSE 4499

CMD ["wisecow.sh"]

