apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: your-namespace
type: kubernetes.io/tls
data:
  tls.crt: |
   LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNzekNDQVpzQ0ZCcDRrK0VoNVBkclhLL2Qv
   STg3c0hkbTJxQlVNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1CWXgKRkRBU0JnTlZCQU1NQ3pNdU9EUXVO
   VEV1TWpBM01CNFhEVEkwTURJd01URTNNRFV5TUZvWERUSTFNREV6TVRFMwpNRFV5TUZvd0ZqRVVN
   QklHQTFVRUF3d0xNeTQ0TkM0MU1TNHlNRGN3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBCkE0SUJE
   d0F3Z2dFS0FvSUJBUURYT0Q3RmxCemlTd2dmQnpWcFZXcW45WjNsR2ZJNEFqazhFcURYajMzVFpR
   VngKc3U0VDJDbENzSmNtK3I4d2FhZ25Nbmx3dXJhMWJLejd2L2dFc3BtY0tCaGhJUHNUYWZqdjdz
   SWtMUDhFQW80cgpFZEtrMzlTTVZCbEZjSFNFTEhsZU1yWXQ5UUI4Nittc1oyZHg4bHJRYWh1SnRC
   Q05oK08wZEUzZ1QvenNzUkJyCm9Ja0RvWFoycnBmcFhjcExQMmtBRnZ1VW5INzRlVjFYb0Y5T0Yy
   OTdybjJ1MnUxT3ZmTnR3RVB3aitYWThVcXEKcmVndnNqdERZa2laeTZjV1B6amtKY1dFR0ZSUDl3
   US9qbTlFQmJ1OVRKRVVSVGZMSnoybktLM0xVZHliUGh3OApwQ2lTOEx6TFN3eDYzUzNRU0ZaMjh4
   eXBETk9yU1RNRjNha0JRNDNWQWdNQkFBRXdEUVlKS29aSWh2Y05BUUVMCkJRQURnZ0VCQUZnTVlk
   bGpYb1FHM1lTaW5oKzYyL1pxZndrVlBKRnp3SjJZTjIzcmF4Ump2QVJnOFV2T1NuaVEKbjRYM05L
   YjE2QkVwa1YxTjVqbUVNTzJET0k2S1BCTW9HdkR6cnlBRk43RTZVTVpWMjZ6dE9qaTRxUXBjLzJ4
   eApEdmI0WWxoMnh6dHJyUEZsUTFxWDc0ODNCeEdyM3R4NC9kRHdYajFNSDZLaU5iaC9zeThwYjF6
   MjNQTlhZVmNUCjFGS0ZsYW1WMm50VUhwT000ZytoUFVoYVp1RGhqQTRUazFZMllmSDRHVmd1MVBr
   YzVLb01TM1hVRjhnaHJZclUKZWM4Qnp6SHhHQk40c3l1U2NnbFdZSmNJWTdjTVFHSHdLRE56TWlI
   ZVBIVGNkaWc0NytSektGc0RMM2JZZG9SNApOZmFjZGRlYWo2YjN3V2tpdVdRekhvVDZVVVlxeXFB
   PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: |
   LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2d0lCQURBTkJna3Foa2lHOXcwQkFRRUZB
   QVNDQktrd2dnU2xBZ0VBQW9JQkFRRFhPRDdGbEJ6aVN3Z2YKQnpWcFZXcW45WjNsR2ZJNEFqazhF
   cURYajMzVFpRVnhzdTRUMkNsQ3NKY20rcjh3YWFnbk1ubHd1cmExYkt6Nwp2L2dFc3BtY0tCaGhJ
   UHNUYWZqdjdzSWtMUDhFQW80ckVkS2szOVNNVkJsRmNIU0VMSGxlTXJZdDlRQjg2K21zCloyZHg4
   bHJRYWh1SnRCQ05oK08wZEUzZ1QvenNzUkJyb0lrRG9YWjJycGZwWGNwTFAya0FGdnVVbkg3NGVW
   MVgKb0Y5T0YyOTdybjJ1MnUxT3ZmTnR3RVB3aitYWThVcXFyZWd2c2p0RFlraVp5NmNXUHpqa0pj
   V0VHRlJQOXdRLwpqbTlFQmJ1OVRKRVVSVGZMSnoybktLM0xVZHliUGh3OHBDaVM4THpMU3d4NjNT
   M1FTRloyOHh5cEROT3JTVE1GCjNha0JRNDNWQWdNQkFBRUNnZ0VBQndZNzdrRHVUR2g4aEY2ODNJ
   cEFKK2s1VlEvcXV1OC9wUGxLcko1dlVlWDcKTG9IVGlXeEZ0SHFGQkcyc3JjelZBeXAva2pGVjQw
   Zi93VnU3b1pPZXRkME5KcVpuNjNOSy83SEFQbVFGa3NEdQptUE5FOThLaWNrNFFZUmJSaHJyWTN6
   MHllditERzVDcm1NZnJOV25la3V6VHAwUHNRbUpNQ1VpK2ZmSytZNDg0CmhUeExDRnhEakhnRFhJ
   ZHRYVU5xQUU2dVpBVVRESHhQZEJxajJOUVJwWFN0b1dSNzRWcEtOM1dlblZ6aVBZWEwKYWlZUkk0
   b2Q2NEZyVSsrOWFLaVJjRnR1aHRQYTg5U29ueGZDU1RCaldTTjMya2ovMG9BTVB2UUtoeTI4UGpO
   cgpCU09sc2NBVFdueVpyWjZGbWJ2WmpBdm1tMWZaRzNoM3Zza09RRU5JQlFLQmdRRCsxT0lJRHVQ
   R0JwaXV2WkltCnJqQzk5U0pNd2VsSmtRQlo0bjB3STVzeUJ5STRML2JObVdzZjVKVnJXRjFtdldK
   YmtCK2dlOVByVXFSODVuRSsKUUkyRUE0ajVZNThTMFgrODV0OUpZQnR5Y3c1cjZsd3pUY1F3cktt
   TXlyVldNYVVib05IanJ2YkVsOHBZMHhNVQp0cGtnT0NYV2lpWmd3ZnZMdjRZTnBaMWEwd0tCZ1FE
   WU5OM1VEbzZMbTVVbk9LQnlWMjNJb3pxN3FqRWJJSFZQCmhwbU9RZFZZcmhPQWZZK1lmTEdMNEZE
   R3c1VUsyUUxMTkxWaHVJRmlUQVNxM1hrZ1lTQm1uVDg0U2RhRHR6M2wKbUl5RHVpOWw4MkFpekxJ
   U0V1S3BoY1d2Q2VwRW1GQnkxcUFGeFQ3azNYVDBCS09JdTY0WjVLQ3NpaFMyUVJTSApVYnhmOVNN
   N3R3S0JnUUM2aVZDUHYzNkNCWEFjY1U0Ym5HUzNtRW9zVDhHYUJWZHhkSFpaRjZkU0hxQ3c2b05L
   CkN1UzhxdEdwaXp5THFWUG5YSCthTlNweVZzTnJYakJFOW5IZzBjbWhiSWdUK1dEOUFTOHZnZmQx
   ZHIxMngwNEkKakFOeDhlSUcycGVVNmJCSG9oZ2lCNEJCZGk4N2gvNnVxZDg3RTM2M0pkZGorbnQ3
   c00zTERaRTYyd0tCZ1FEUApqYURPYTlNSHpxblc1eE9QOE1KaGMrRjBPcU85aU9GVklML1V3dnBP
   a1g0RFFZWlNPcEl1MTM1ejhWbm8rZjhtCm1FanZzTEgwYlVtbHhjcjcvSUdnUUtCcUp1Z1p0aFZq
   alppRzlIdUFBYTF1ZXRjUFpyWFZTNmhFcXQ0TVQ3UWIKS2xLZ2Q0UXpMUzJTKzhrS0FESFloWlNC
   VG1VbnVUNDkwWWRuRHV0dDdRS0JnUUNkUWwvZE01c0lQUlMrMzdZVwpmdzJNY09vS3I5d0xoRG9Q
   OWhvRUFmWnJMVjkrZVJSZGppV2pheFJPaWlsODdtMW1qQTFObE1vdnV5WCtxbG5hCjRIdGthd2lR
   WVM1eFlXSEZLSFFyd3pLYmhWaCtsd3h1ekU2NjFqQ2hLczlqakVyZ0VuVWZXUWNFdDV6LzFPZjkK
   TlZXUWR6Q0lZK2U3dm5FclZsN2RoZmtYaUE9PQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==

