apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
  namespace: your-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow-container
        image: shrey871/wisecow-app:latest
        ports:
        - containerPort: 4499
        volumeMounts:
          - name: tls-certs
            mountPath: /etc/tls
            readOnly: true
      volumes:
        - name: tls-certs
          secret:
            secretName: TLS-secret
        
