name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.shrey871 }}
          password: ${{ secrets.dckr_pat_9IIxSKbT5UuKIJlV-CRjQcqsxxQ}}

      - name: Build and push Docker image
        run: |
          docker build -t wisecow-shrey:latest .
          docker tag wisecow-shrey:latest ${{ secrets.shrey871 }}/shrey871/wisecow-shrey:latest
          docker push ${{ secrets.shrey871 }}/shrey871/wisecow-shrey:latest

