name: Build Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
  
      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap
          pwd
          ls /home/runner/work/Wisecow-app/Wisecow-app/wisecow-app/
          ls /home/runner/work/Wisecow-app/Wisecow-app/wisecow-app/
          DOCKER_BUILTKIT=0 docker buildx build --platform linux/amd64,linux/arm64 -t shrey871/wisecow-app:latest -f /home/runner/work/Wisecow-app/Wisecow-app/wisecow-app/dockerfile . --push
      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v1
        with:
          creds: ${{ secrets.KUBE_CONFIG }}
          image: shrey871/wisecow-app:latest
          namespace: your-namespace
          deployment: wisecow-deployment
          manifests: |
            /home/runner/work/Wisecow-app/Wisecow-app/wisecow-app/kubernetes-wisecow/wisecow-deployment.yml
  
