name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy to Kubernetes
        run: |
          pwd 
          kubectl cluster-info
          kubectl get nodes
          kubectl version
          ls /home/runner/work/Wisecow-app/Wisecow-app/wisecow-app/kubernetes-wisecow
          kubectl set image deployment/wisecow-deployment.yml wisecow-container=shrey871/wisecow-app:latest
          
        env:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
