name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy to Kubernetes
        run: |
          pwd 
          
          ls /home/runner/work/Wisecow-app/Wisecow-app/wisecow-app/kubernetes-wisecow
          # kubectl set image deployment/wisecow-deployment wisecow-container=shrey871/wisecow-app:latest
          # kubectl rollout status deployment/wisecow-deployment
          kubectl apply -f /home/runner/work/Wisecow-app/Wisecow-app/wisecow-app/kubernetes-wisecow/wisecow-namespace.yml --validate=false
          kubectl apply -f /home/runner/work/Wisecow-app/Wisecow-app/wisecow-app/kubernetes-wisecow/wisecow-deployment.yml --validate=false
          kubectl apply -f /home/runner/work/Wisecow-app/Wisecow-app/wisecow-app/kubernetes-wisecow/wisecow-pods.yml --validate=false
          kubectl apply -f /home/runner/work/Wisecow-app/Wisecow-app/wisecow-app/kubernetes-wisecow/wisecow-svc.yml --validate=false
          kubectl apply -f /home/runner/work/Wisecow-app/Wisecow-app/wisecow-app/kubernetes-wisecow/wisecow-ingress.yml --validate=false
          kubectl apply -f /home/runner/work/Wisecow-app/Wisecow-app/wisecow-app/kubernetes-wisecow/TLS-secret.yml --validate=false
          # Add additional apply commands for other YAML files if needed
        env:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
