name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy to Kubernetes
        env:
           KUBECONFIG_FILE: ${{ secrets.KUBE_CONFIG }}
           KUBE_NAMESPACE: your-k8s-namespace
           KUBE_CONTEXT: kubernetes-admin@kubernetes 
        run: |
          pwd 
          echo "$KUBECONFIG_FILE" > kubeconfig.yml
          cat kubeconfig.yaml  # Print the kubeconfig file content (added step)
          kubectl config use-context $KUBE_CONTEXT --kubeconfig=kubeconfig.yml
          kubectl apply --kubeconfig=kubeconfig.yml --namespace=$KUBE_NAMESPACE -f wisecow_deploy.yml
          ls /home/runner/work/Wisecow-app/Wisecow-app/wisecow-app/kubernetes-wisecow
          # kubectl set image deployment/wisecow-deployment wisecow-container=shrey871/wisecow-app:latest
          # kubectl rollout status deployment/wisecow-deployment
          # kubectl apply -f /home/runner/work/Wisecow-app/Wisecow-app/wisecow-app/kubernetes-wisecow/ --validate=false
          # Add additional apply commands for other YAML files if needed
